(deffacts Objects 
    (Description (ID John)
        (Features Tail Yes Wool Yes Color White)
    )
    (Description (ID Mary)
        (Features Tail No Wool No)
    )
    (Description (ID Ivan)
        (Features Tail No Wool Yes Color Black)
    )
    (Description (ID Ann)
        (Features Wool No)
    )
    (Description (ID Anonimous) (Features ))
)
